<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AiKnowledgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'question' => 'Maktab qachon tashkil topgan?',
                'question_en' => 'When was the school established?',
                'answer' => '81-IDUM maktabi o\'z faoliyatini 1980-yillarda boshlagan va hozirda zamonaviy ta\'lim markazlaridan biri hisoblanadi.',
                'answer_en' => 'School 81-IDUM started its activity in the 1980s and is now one of the modern educational centers.',
                'keywords' => 'tashkil, qachon, ochilgan, sana, yil',
            ],
            [
                'question' => 'Maktab manzili qayerda?',
                'question_en' => 'Where is the school located?',
                'answer' => 'Maktabimiz Toshkent viloyati, Zangiota tumanida joylashgan. Batafsil xaritani "Aloqa" bo\'limidan topishingiz mumkin.',
                'answer_en' => 'Our school is located in Zangiota district, Tashkent region. You can find a detailed map in the "Contact" section.',
                'keywords' => 'manzil, qayerda, joylashgan, lokatsiya, xarita',
            ],
            [
                'question' => 'Qanday fanlar o\'tiladi?',
                'question_en' => 'What subjects are taught?',
                'answer' => 'Maktabimizda barcha davlat standartidagi fanlar bilan birga IT, Matematika va Ingliz tili chuqurlashtirib o\'tiladi.',
                'answer_en' => 'In our school, IT, Mathematics and English are taught in depth along with all state standard subjects.',
                'keywords' => 'fanlar, darslar, nimalar, o\'qitiladi',
            ],
            [
                'question' => 'Sayt muallifi kim?',
                'question_en' => 'Who created the website?',
                'answer' => 'Ushbu sayt 10-"E" sinf o\'quvchilari tomonidan ishlab chiqilgan. Mualliflar: Xabibullayev Shamsiddin, Abduqodirova E\'zoza va Mirzaqosimova Xadicha.',
                'answer_en' => 'This website was developed by Grade 10-E students: Shamsiddin Khabibullayev, E\'zoza Abdukodirova and Xadicha Mirzakosimova.',
                'keywords' => 'sayt, muallif, yaratgan, dasturchi, developer, ishtirok, jamoa',
                'category' => 'Sayt',
                'sort_order' => -20,
            ],
            [
                'question' => 'AI yordamchi nimalarga javob beradi?',
                'question_en' => 'What can the AI assistant answer?',
                'answer' => "AI yordamchi maktab ma'lumotlari, sayt mualliflari, yangiliklar, ustozlar, kurslar, imtihonlar, natijalar, taqvim, aloqa, admin bilan bog'lanish, profil, akkaunt, chat va izohlar bo'yicha javob berishga harakat qiladi.",
                'answer_en' => 'The AI assistant can help with school information, website credits, news, teachers, courses, exams, results, calendar, support/contact, profile and general study questions.',
                'keywords' => 'ai, yordamchi, nima qiladi, savol, javob, imkoniyat',
                'category' => 'AI',
                'sort_order' => -10,
            ],
            [
                'question' => 'Saytda qanday savollar berish mumkin?',
                'question_en' => 'What questions can I ask on the site?',
                'answer' => "Quyidagi turdagi savollarni berishingiz mumkin:\n- maktab haqida\n- sayt mualliflari haqida\n- ustozlar va fanlar haqida\n- kurslar va arizalar haqida\n- imtihon va natijalar haqida\n- taqvim va tadbirlar haqida\n- aloqa, admin va support haqida\n- profil, parol va email sozlamalari haqida\n- chat va izohlar haqida",
                'answer_en' => 'You can ask about school information, website credits, teachers, courses, exams, calendar events, support, account settings and contact details.',
                'keywords' => 'qanday savollar, qanaqa savollar, nima deb sorasam, yordamchi savollar, faq',
                'category' => 'AI',
                'sort_order' => -9,
            ],
            [
                'question' => 'Saytda nimalar bor?',
                'question_en' => 'What sections are on the website?',
                'answer' => "Saytda quyidagi asosiy bo'limlar bor:\n- Yangiliklar\n- Ustozlar\n- Kurslar\n- Imtihonlar\n- Taqvim\n- Aloqa\n- Profil\n- Global chat\n- AI yordamchi\n- Izohlar va like'lar\n- Admin panel",
                'answer_en' => 'The site contains news, teachers, courses, exams, calendar, contact, profile, chat, AI and admin sections.',
                'keywords' => 'saytda nima bor, sayt bolimlari, sahifalar, bo limlar, sections',
                'category' => 'Sayt',
                'sort_order' => -8,
            ],
            [
                'question' => 'Maktab telefon raqami nima?',
                'question_en' => 'What is the school phone number?',
                'answer' => "Maktab bilan bog'lanish uchun telefon raqamini Aloqa bo'limidan olishingiz mumkin. Zarur bo'lsa rasmiy email va manzil ham shu sahifada ko'rsatiladi.",
                'answer_en' => 'You can find the official phone number on the Contact page.',
                'keywords' => 'telefon, raqam, nomer, aloqa, contact',
                'category' => 'Aloqa',
            ],
            [
                'question' => 'Parolni unutdim, nima qilaman?',
                'question_en' => 'I forgot my password. What should I do?',
                'answer' => "Kirish sahifasidagi \"Parolni unutdingizmi?\" bo'limiga o'ting. Email manzilingizni kiriting, tasdiqlash kodini oling va yangi parol qo'ying.",
                'answer_en' => 'Use the forgot password page, enter your email, verify the code, and set a new password.',
                'keywords' => 'parol, unutdim, forgot password, reset password, kod',
                'category' => 'Akkaunt',
            ],
            [
                'question' => 'Ro\'yxatdan qanday o\'taman?',
                'question_en' => 'How do I register?',
                'answer' => "Ro'yxatdan o'tish uchun Register sahifasini oching, ism, email va parolni kiriting. So'ng emailga yuborilgan tasdiqlash kodi orqali akkauntni faollashtiring.",
                'answer_en' => 'Open the Register page, fill in your details, and verify your account with the emailed code.',
                'keywords' => 'register, royxatdan, ro yxatdan, signup, account yaratish',
                'category' => 'Akkaunt',
            ],
            [
                'question' => 'Profil bo\'limida nimalar bor?',
                'question_en' => 'What is inside the profile section?',
                'answer' => "Profil bo'limida shaxsiy ma'lumotlar, email va parol sozlamalari, imtihon natijalari, kurs arizalari va sizning rolingizga qarab qo'shimcha boshqaruv bo'limlari bor.",
                'answer_en' => 'The profile section contains personal settings, exam results, course requests and role-based tools.',
                'keywords' => 'profil, profile, bo lim, nimalar bor, account settings',
                'category' => 'Profil',
            ],
            [
                'question' => 'Kursga qanday yozilaman?',
                'question_en' => 'How can I enroll in a course?',
                'answer' => "Kurslar bo'limidan kerakli kursni tanlang va yozilish tugmasini bosing. Ariza yuborilgach, kurs muallifi uni ko'rib chiqadi.",
                'answer_en' => 'Open the course page and click enroll. The course creator will review your request.',
                'keywords' => 'kursga yozilish, enroll, ariza, kursga kirish',
                'category' => 'Kurslar',
            ],
            [
                'question' => 'Imtihon natijamni qayerdan ko\'raman?',
                'question_en' => 'Where can I see my exam result?',
                'answer' => "Imtihon natijangizni Profil bo'limidan yoki imtihon yakunlangandan keyin ochiladigan natija sahifasidan ko'rishingiz mumkin.",
                'answer_en' => 'You can see your exam result on the profile page or on the result page after finishing the exam.',
                'keywords' => 'natijam, imtihon natija, result, ballim, exam result',
                'category' => 'Imtihonlar',
            ],
            [
                'question' => 'Imtihonlarda nimalar qilish mumkin?',
                'question_en' => 'What can be done in exams?',
                'answer' => "Saytda imtihonni boshlash, savollarga javob berish, matnli javob yuborish, vaqt tugagach natijani ko'rish va ayrim rollarda natijalarni boshqarish imkoniyati bor.",
                'answer_en' => 'Users can start exams, answer questions, submit text answers and view results; some roles can manage exam results.',
                'keywords' => 'imtihon, exam, nima qiladi, savollar, javob berish',
                'category' => 'Imtihonlar',
            ],
            [
                'question' => 'Yangiliklarni qayerdan ko\'raman?',
                'question_en' => 'Where can I read the news?',
                'answer' => "Yangiliklarni News/Post bo'limidan ko'rishingiz mumkin. U yerda qidiruv, kategoriya va material tafsilotlari mavjud.",
                'answer_en' => 'You can read the news in the Posts section with search and category filters.',
                'keywords' => 'yangilik, news, post, maqola, e lon, elon',
                'category' => 'Yangiliklar',
            ],
            [
                'question' => 'Taqvimda nimalar chiqadi?',
                'question_en' => 'What appears in the calendar?',
                'answer' => "Taqvim bo'limida maktab tadbirlari, sanaga bog'liq e'lonlar va yaqinlashayotgan voqealar ko'rsatiladi.",
                'answer_en' => 'The calendar shows school events and date-based announcements.',
                'keywords' => 'taqvim, calendar, tadbir, sana, voqea',
                'category' => 'Taqvim',
            ],
            [
                'question' => 'Ustozlar haqida nima so\'rash mumkin?',
                'question_en' => 'What can I ask about teachers?',
                'answer' => "Ustozlar haqida ism bo'yicha, fani bo'yicha, lavozimi bo'yicha yoki tajribasi haqida so'rashingiz mumkin. Masalan: \"Matematika o'qituvchisi kim?\" yoki \"Falon ustoz kim?\"",
                'answer_en' => 'You can ask about teachers by name, subject, role or experience.',
                'keywords' => 'ustozlar, oqituvchi, o qituvchi, fani, lavozimi, teacher faq',
                'category' => 'Ustozlar',
            ],
            [
                'question' => 'Aloqa bo\'limi nima uchun?',
                'question_en' => 'What is the contact section for?',
                'answer' => "Aloqa bo'limi orqali maktabga savol yuborish, murojaat qoldirish va rasmiy manzil yoki aloqa ma'lumotlarini ko'rish mumkin.",
                'answer_en' => 'The contact section is for sending messages and checking official contact details.',
                'keywords' => 'aloqa, contact, murojaat, xabar, message',
                'category' => 'Aloqa',
            ],
            [
                'question' => 'Global chat nima?',
                'question_en' => 'What is the global chat?',
                'answer' => "Global chat foydalanuvchilar uchun umumiy muloqot oynasi. U yerda tezkor xabarlar va stikerlar yuborish mumkin, lekin admin sozlamasiga qarab vaqtincha yopilishi ham mumkin.",
                'answer_en' => 'Global chat is a shared conversation panel for users and may be temporarily disabled by admins.',
                'keywords' => 'global chat, chat nima, umumiy chat, stiker',
                'category' => 'Chat',
            ],
            [
                'question' => 'Admin bilan qanday bog\'lansam bo\'ladi?',
                'question_en' => 'How can I contact the admin?',
                'answer' => "Admin bilan bog'lanish uchun Aloqa sahifasiga kiring va murojaat yuboring. Xabar yuborish uchun akkauntga kirgan bo'lishingiz kerak. Murojaatlar super admin, admin va moderatorlar tomonidan ko'rib chiqiladi. Shoshilinch holatda rasmiy telefon yoki emaildan foydalaning.",
                'answer_en' => 'Use the Contact page while signed in. Messages are reviewed by the super admin, admins or moderators.',
                'keywords' => 'admin bilan boglanish, adminga yozish, support, texnik yordam, murojaat, contact admin',
                'category' => 'Aloqa',
                'sort_order' => -7,
            ],
            [
                'question' => 'Murojaatimni kim ko\'radi?',
                'question_en' => 'Who can see my support message?',
                'answer' => "Aloqa bo'limi orqali yuborilgan murojaatlar super admin, admin va moderatorlar tomonidan ko'rib chiqiladi.",
                'answer_en' => 'Messages sent through the contact section are reviewed by the super admin, admins and moderators.',
                'keywords' => 'murojaatni kim koradi, kim ko radi, contact message, admin koradi',
                'category' => 'Aloqa',
            ],
            [
                'question' => 'Xabar yuborish uchun tizimga kirish kerakmi?',
                'question_en' => 'Do I need to sign in to send a contact message?',
                'answer' => "Ha. Aloqa formasidan xabar yuborish uchun tizimga kirgan bo'lishingiz kerak. Bu siz bilan qayta bog'lanishni osonlashtiradi.",
                'answer_en' => 'Yes. You need to be signed in to use the contact form.',
                'keywords' => 'login kerakmi, tizimga kirish, xabar yuborish, aloqa forma',
                'category' => 'Aloqa',
            ],
            [
                'question' => 'Admin javobi qayerdan keladi?',
                'question_en' => 'How will the admin reply to me?',
                'answer' => "Javob odatda emailingiz yoki qoldirgan aloqa ma'lumotingiz orqali beriladi. Shuning uchun profil ma'lumotlaringiz to'g'ri bo'lishi muhim.",
                'answer_en' => 'Replies usually come through your email or the contact details linked to your account.',
                'keywords' => 'admin javobi, javob qayerdan, emailga keladimi, reply',
                'category' => 'Aloqa',
            ],
            [
                'question' => 'Texnik muammo bo\'lsa nima qilaman?',
                'question_en' => 'What should I do if I have a technical problem?',
                'answer' => "Aloqa bo'limidan murojaat yuboring va qaysi sahifada, qaysi tugmani bosganda yoki qanday xato chiqqanini yozing. Iloji bo'lsa qurilma yoki brauzer haqida ham yozing.",
                'answer_en' => 'Send a message through the Contact page and describe the page, action and error clearly.',
                'keywords' => 'texnik muammo, bug, xato, support, yordam',
                'category' => 'Aloqa',
            ],
            [
                'question' => 'Maktab emaili nima?',
                'question_en' => 'What is the school email address?',
                'answer' => "Rasmiy email manzilini Aloqa bo'limida ko'rishingiz mumkin. Odatda murojaatlar shu yerda ko'rsatilgan rasmiy email orqali ham yuboriladi.",
                'answer_en' => 'You can find the official school email in the Contact section.',
                'keywords' => 'maktab emaili, school email, aloqa email, pochta',
                'category' => 'Aloqa',
            ],
            [
                'question' => 'Murojaatda nimalarni yozsam yaxshi bo\'ladi?',
                'question_en' => 'What should I include in my support message?',
                'answer' => "Murojaatda mavzuni qisqa yozing va matnda muammoni aniq tushuntiring. Masalan: qaysi sahifada xato chiqqani, qachon bo'lgani va sizdan qanday yordam kerakligi.",
                'answer_en' => 'Write a short subject and clearly explain the issue, page and help you need.',
                'keywords' => 'murojaatda nima yozaman, contact form, subject, xabar matni',
                'category' => 'Aloqa',
            ],
            [
                'question' => 'Emailni qanday o\'zgartiraman?',
                'question_en' => 'How do I change my email?',
                'answer' => "Profil bo'limidagi email kartasidan yangi email kiriting, kod oling va tasdiqlash kodini kiritib yangilang.",
                'answer_en' => 'Use the email card in your profile, request a code and verify the new address.',
                'keywords' => 'emailni ozgartirish, profil email, yangi email, email almashtirish',
                'category' => 'Profil',
            ],
            [
                'question' => 'Yangi emailga kod kelmasa nima qilaman?',
                'question_en' => 'What if the verification code does not arrive to my new email?',
                'answer' => "Avval emailni to'g'ri kiritganingizni tekshiring. So'ng Profil bo'limidagi qayta yuborish tugmasidan foydalaning. Zarur bo'lsa email almashtirishni bekor qilib, qaytadan boshlang.",
                'answer_en' => 'Check the email address, use resend in your profile, or cancel and start the email change again.',
                'keywords' => 'email kod kelmadi, resend, qayta yuborish, pending email',
                'category' => 'Profil',
            ],
            [
                'question' => 'Kurs arizam holatini qayerdan ko\'raman?',
                'question_en' => 'Where can I see the status of my course request?',
                'answer' => "Kursga yozilgandan keyin holat kurs sahifasida yoki profilingizdagi tegishli bo'limlarda ko'rinadi. Tasdiqlangan, kutilmoqda yoki rad etildi holatlari bo'lishi mumkin.",
                'answer_en' => 'After applying, the status appears on the course page or in the related profile area.',
                'keywords' => 'kurs ariza holati, enrollment status, pending, approved, rejected',
                'category' => 'Kurslar',
            ],
            [
                'question' => 'Kurs arizamni kim tasdiqlaydi?',
                'question_en' => 'Who approves my course enrollment request?',
                'answer' => "Odatda kursga yozilish arizasini kurs muallifi ko'rib chiqadi. Zarurat bo'lsa adminlar ham kurs yozilishlarini boshqarishi mumkin.",
                'answer_en' => 'Course enrollments are usually reviewed by the course owner, and admins may also manage them.',
                'keywords' => 'kursni kim tasdiqlaydi, ariza kim koradi, enrollment approve',
                'category' => 'Kurslar',
            ],
            [
                'question' => 'Imtihon natijam ko\'rinmasa nima qilaman?',
                'question_en' => 'What should I do if my exam result is not visible?',
                'answer' => "Avval imtihon yakunlanganini tekshiring. Natija Profil bo'limida yoki imtihon tugagach ochilgan sahifada ko'rinadi. Hali chiqmagan bo'lsa o'qituvchi yoki admin tekshiruvi tugamagan bo'lishi mumkin.",
                'answer_en' => 'Check whether the exam is finished. Results appear in the profile or on the result page after submission.',
                'keywords' => 'natija korinmayapti, result yoq, exam result problem',
                'category' => 'Imtihonlar',
            ],
            [
                'question' => 'Global chat o\'chib qolsa nima qilaman?',
                'question_en' => 'What if the global chat is disabled?',
                'answer' => "Global chat vaqtincha admin sozlamalari orqali o'chirilgan bo'lishi mumkin. Keyinroq urinib ko'ring yoki muhim masala bo'lsa Aloqa bo'limidan murojaat yuboring.",
                'answer_en' => 'The global chat may be temporarily disabled by admins. Try again later or use the Contact page for urgent issues.',
                'keywords' => 'chat ochilmayapti, global chat ochmayapti, chat off',
                'category' => 'Chat',
            ],
            [
                'question' => 'Izohni tahrirlasa yoki o\'chirsa bo\'ladimi?',
                'question_en' => 'Can comments be edited or deleted?',
                'answer' => "Ha. O'zingiz yozgan post yoki ustoz izohlarini tahrirlash va o'chirish mumkin. Moderator va adminlar ham qoidalarga zid izohlarni boshqarishi mumkin.",
                'answer_en' => 'Yes. Your own post or teacher comments can be edited or deleted, and staff can moderate them too.',
                'keywords' => 'izohni tahrirlash, comment edit, comment delete, like',
                'category' => 'Izohlar',
            ],
            [
                'question' => 'Saytda izoh qoldirsa bo\'ladimi?',
                'question_en' => 'Can I leave comments on the site?',
                'answer' => "Ha. Yangiliklar va ustozlar sahifalarida izoh yozish, javob qoldirish va ayrim joylarda like bosish mumkin.",
                'answer_en' => 'Yes. You can comment on news and teacher pages, reply, and use likes in supported places.',
                'keywords' => 'izoh qoldirish, comment yozish, like bosish',
                'category' => 'Izohlar',
            ],
            [
                'question' => 'Admin panelga kim kira oladi?',
                'question_en' => 'Who can access the admin panel?',
                'answer' => "Admin panelga ruxsat roli berilgan foydalanuvchilar kiradi. Rolga qarab super admin, admin, moderator yoki editor bo'limlari ochiladi.",
                'answer_en' => 'Users with staff roles can access the admin panel with sections based on their role.',
                'keywords' => 'admin panelga kim kiradi, admin rol, moderator, editor',
                'category' => 'Panel',
            ],
            [
                'question' => 'Moderator nima ish qiladi?',
                'question_en' => 'What does a moderator do?',
                'answer' => "Moderator aloqa xabarlarini ko'radi, izohlarni boshqaradi va sayt tartibini saqlashga yordam beradi. Odatda system sozlamalari yoki to'liq admin boshqaruvi moderator vakolatiga kirmaydi.",
                'answer_en' => 'A moderator reviews contact messages, manages comments and helps maintain order on the site.',
                'keywords' => 'moderator, moderato, modirator, moderator vazifasi, moderator nima qiladi',
                'category' => 'Panel',
            ],
            [
                'question' => 'Editor nima ish qiladi?',
                'question_en' => 'What does an editor do?',
                'answer' => "Editor asosan kontent bilan ishlaydi: postlar, kategoriyalar va taqvim materiallarini boshqaradi, tahrir qiladi va nashrga tayyorlaydi.",
                'answer_en' => 'An editor mainly manages content such as posts, categories and calendar items.',
                'keywords' => 'editor, editr, editor vazifasi, editor nima qiladi',
                'category' => 'Panel',
            ],
            [
                'question' => 'Admin nima ish qiladi?',
                'question_en' => 'What does an admin do?',
                'answer' => "Admin saytning asosiy boshqaruv bo'limlari bilan ishlaydi: ustozlar, imtihonlar, kurslar, aloqa xabarlari va comment moderatsiyasini nazorat qiladi.",
                'answer_en' => 'An admin manages the main control sections such as teachers, exams, courses, inbox and moderation.',
                'keywords' => 'admin nima qiladi, administrator vazifasi, admin vazifasi',
                'category' => 'Panel',
            ],
            [
                'question' => 'Super admin nima ish qiladi?',
                'question_en' => 'What does the super admin do?',
                'answer' => "Super admin tizimning eng yuqori darajadagi boshqaruvchisidir. U sozlamalar, AI bilim bazasi, foydalanuvchilar va admin bo'limlarini to'liq boshqaradi.",
                'answer_en' => 'The super admin has the highest system privileges and full control over settings, AI knowledge and users.',
                'keywords' => 'super admin nima qiladi, superadmin, super admin vazifasi',
                'category' => 'Panel',
            ],
            [
                'question' => 'Teacher panelda nima qilish mumkin?',
                'question_en' => 'What can be done in the teacher panel?',
                'answer' => "Teacher yoki kurs egasi o'z kurslarini ochishi, tasdiqlash kodi orqali nashr qilishi, yozilishlarni ko'rishi va ularni tasdiqlashi yoki rad etishi mumkin.",
                'answer_en' => 'Teachers or course owners can create courses, verify publication and manage enrollments.',
                'keywords' => 'teacher panel, teacher nima qiladi, course open, enrollment approve',
                'category' => 'Panel',
            ],
            [
                'question' => 'Bu sayt nima uchun kerak?',
                'question_en' => 'What is this website for?',
                'answer' => "Bu sayt maktabning asosiy raqamli platformasi. U yangiliklar, ustozlar, kurslar, imtihonlar, natijalar, taqvim, aloqa, profil va admin boshqaruvini bir joyga jamlaydi.",
                'answer_en' => 'This website is the school’s main digital platform for news, teachers, courses, exams, profile and administration.',
                'keywords' => 'sayt nima uchun kerak, nimaga kerak, sayt vazifasi, sayt maqsadi',
                'category' => 'Sayt',
                'sort_order' => -19,
            ],
            [
                'question' => 'Saytning vazifasi nima?',
                'question_en' => 'What is the purpose of the website?',
                'answer' => "Saytning vazifasi maktabga oid bo'limlarni bir joyga yig'ish va o'quvchi, ota-ona, ustoz hamda adminlar uchun qulay boshqaruv muhiti yaratishdir.",
                'answer_en' => 'The site’s purpose is to bring school sections together and provide a convenient digital environment.',
                'keywords' => 'sayt vazifasi, sayt maqsadi, bu sayt nima qiladi',
                'category' => 'Sayt',
            ],
            [
                'question' => 'Saytda AI\'ga qanday savollar bersam bo\'ladi?',
                'question_en' => 'What example questions can I ask the AI on this site?',
                'answer' => "Masalan shunday savollar bersangiz bo'ladi:\n- admin bilan qanday bog'lanaman?\n- sayt muallifi kim?\n- kursga qanday yozilaman?\n- imtihon natijam qayerda?\n- emailimni qanday o'zgartiraman?\n- global chat nima?\n- ustozlar ro'yxati bormi?",
                'answer_en' => 'Example questions include support, site credits, courses, exams, email settings, chat and teachers.',
                'keywords' => 'ai ga savol, misol savollar, nimalar sorash mumkin',
                'category' => 'AI',
            ],
        ];

        foreach ($data as $item) {
            \App\Models\AiKnowledge::updateOrCreate(
                ['question' => $item['question']],
                $item
            );
        }
    }
}
