services:
  - type: web
    name: 81-maktab
    env: php
    buildCommand: composer install --no-dev && php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
