# OSPanel: Laravel routing for localhost/81-maktab/public
location /81-maktab/public/ {
    try_files $uri $uri/ /81-maktab/public/index.php?$query_string;
}

location ~ ^/81-maktab/public/.*\.php$ {
    try_files      $fastcgi_script_name =404;
    fastcgi_pass   backend;
    include        '%sprogdir%/userdata/config/nginx_fastcgi_params.txt';
}
